spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  activemq:
    broker-url: tcp://127.0.0.1:61616    # ActiveMQ消息中间件服务器通讯地址
    user: admin  # 用户名
    password:  #密码
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0

queue: springboot-queue   #自定义队列名，等下程序中会用到

logging:
  level:
    root: info
    com.lsy: info
  #file: log/blog-dev.log
server:
  port: 8080
